### ISSUE TITLE
[ BUG] FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib64/python3.11'

### ISSUE THREAD

**Issue by CaedenPH** [PyCQA/autoflake#216]
Error when running `autoflake` in terminal - 
```
Traceback (most recent call last):
  File "/home/Caeden/.local/bin/autoflake", line 5, in <module>
    from autoflake import main
  File "/home/Caeden/.local/lib/python3.11/site-packages/autoflake.py", line 105, in <module>
    frozenset(standard_package_names()) - IMPORTS_WITH_SIDE_EFFECTS | BINARY_IMPORTS
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Caeden/.local/lib/python3.11/site-packages/autoflake.py", line 75, in standard_package_names
    for name in standard_paths():
  File "/home/Caeden/.local/lib/python3.11/site-packages/autoflake.py", line 65, in standard_paths
    yield from os.listdir(path)
               ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib64/python3.11'
```
**Python version:** `3.11`
**OS:** `Fedora`

**Comment by fsouza** [comment]
Hey there, thanks for reporting.

This appears to be an issue with your setup. Please provide more details on how you installed autoflake and we can help pin it down.

**Comment by CaedenPH** [comment]
> 

Just ran `pip install autoflake` 
It says the version of `autoflake` is `2.0.0`, which is latest

**Comment by fsouza** [comment]
Oh ok I see what's going on. Surprised that this is the first time this fails. Can you try #217?
