### ISSUE TITLE
MultiProcessing issue

### ISSUE THREAD

**Issue by orestis-z** [PyCQA/autoflake#266]
Pre-commit hook config:
```yaml
- repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    - id: autoflake
      args:
      - "--in-place"
      - "--expand-star-imports"
      - "--remove-duplicate-keys"
      - "--remove-unused-variables"
      - "--remove-all-unused-imports"
```

Error:

```
Traceback (most recent call last):
  File "/home/sv/.cache/pre-commit/repocja7_r8q/py_env-python3/bin/autoflake", line 8, in <module>
    sys.exit(main())
  File "/home/sv/.cache/pre-commit/repocja7_r8q/py_env-python3/lib/python3.8/site-packages/autoflake.py", line 1587, in main
    return _main(
  File "/home/sv/.cache/pre-commit/repocja7_r8q/py_env-python3/lib/python3.8/site-packages/autoflake.py", line 1562, in _main
    with multiprocessing.Pool(args["jobs"]) as pool:
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 191, in __init__
    self._setup_queues()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 343, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
FileNotFoundError: [Errno 2] No such file or directory
```

Getting the same error when setting `--jobs 1` in the pre-commit config, and also when running `autoflake` in the CLI with the `--recursive` flag.

**Comment by fsouza** [comment]
@orestis-z this is unexpected. Can you provide more details on your environment?

**Comment by orestis-z** [comment]
Closing this because it's due to my environment and not your package, sorry for the confusion
